import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Product, FooterBanner, HeroBanner, Footer, Navbar } from "../components";
import { client } from "../lib/client";

export default function Home({ products, bannerData }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <HeroBanner heroBanner={bannerData.length && bannerData[0]} />
        <div className="text-center ">
          <h2 className="text-black/60 font-bold text-4xl">
            Best Selling Products
          </h2>
          <p>Fruits Of many Variations</p>
        </div>
        <div className="flex flex-wrap justify-center space-x-3 top-4 w-full">
          {products?.map((product) => (
            <Product key={product._id} product={product} />
          ))}
        </div>
      </main>
    </div>
  );
}

export const getServerSideProps = async () => {
  const query = '*[_type == "product"]';
  const products = await client.fetch(query);

  const bannerQuery = '*[_type == "banner"]';
  const bannerData = await client.fetch(bannerQuery);

  return {
    props: { products, bannerData },
  };
};
